# Project configuration for Clippy Rust code linter.
# See full lints list at:
# https://rust-lang.github.io/rust-clippy/master/index.html

doc-valid-idents = ["JUnit"]

standard-macro-braces = [
    { name = "assert", brace = "(" },
    { name = "assert_eq", brace = "(" },
    { name = "assert_ne", brace = "(" },
    { name = "format", brace = "(" },
    { name = "format_ident", brace = "(" },
    { name = "panic", brace = "(" },
    { name = "quote", brace = "{" },
    { name = "vec", brace = "[" },
]
