# Project configuration for Clippy Rust code linter.
# See full lints list at:
# https://rust-lang.github.io/rust-clippy/master/index.html

doc-valid-idents = ["JUnit"]

standard-macro-braces = [
    { name = "assert", brace = "(" },
    { name = "assert_eq", brace = "(" },
    { name = "assert_ne", brace = "(" },
    { name = "debug_assert", brace = "(" },
    { name = "debug_assert_eq", brace = "(" },
    { name = "debug_assert_ne", brace = "(" },
    { name = "format", brace = "(" },
    { name = "format_args", brace = "(" },
    { name = "format_ident", brace = "(" },
    { name = "matches", brace = "(" },
    { name = "panic", brace = "(" },
    { name = "parse_quote", brace = "{" },
    { name = "print", brace = "(" },
    { name = "println", brace = "(" },
    { name = "quote", brace = "{" },
    { name = "quote_spanned", brace = "{" },
    { name = "vec", brace = "[" },
    { name = "write", brace = "(" },
    { name = "writeln", brace = "(" },
]

type-complexity-threshold = 300
